# Field flags
FIELD_TYPE_IP_GHASH = 0x20
FIELD_FLAG_CNT = 0x02
FIELD_FLAG_NODB = 0x04  # 数据库字段标志位
FIELD_FLAG_DISABLED = 0x20  # 禁用字段标志位
FIELD_FLAG_IPPRE = 0x08
FIELD_FLAG_FAKE = 0x01  # 虚拟字段标志位
FIELD_TYPE_STR_HASH = 0x40  # 字符串哈希表类型
FIELD_FLAG_FORCE_UTF8 = 0x10  # 强制UTF8编码标志
FIELD_TYPE_IP = 1
FIELD_TYPE_STRING = 3
FIELD_FLAG_ECS_CNT = 0x40  # ECS风格计数字段标志
FIELD_MAX_JSON_SIZE = 20000
FIELD_MAX_ELEMENT_SIZE = 16384

# Additional field types
FIELD_TYPE_STR_ARRAY = 0x80  # 字符串数组类型
FIELD_TYPE_INT_GHASH = 0x100  # 整型哈希表类型
FIELD_TYPE_STR_GHASH = 0x200  # 字符串全局哈希表类型
FIELD_TYPE_INT = 2  # 整型类型 